### PR TITLE
Issue #98: Support "stop_on_error" option for bulk inserts (default: TRUE)

### PR DESCRIPTION
**Pull request by stennie**

### CODE REVIEW

**Comment by jeroen** [comment]
Perhaps this is easier to expose as a global setting than an insert parameter? We could add an option `stop_on_error` to `mongo_options()` to set this globally so we don't have to pass around the parameter between functions?

Does that make sense, or is `stop_on_error` typically something you want for one insert but not for another?

**Comment by stennie** [comment]
With other MongoDB drivers this is typically specified per bulk operation rather than as a global setting.

I think a global setting might be nice for convenience, but personally I'd prefer the option to change rather than having to create a new client instance. It probably makes sense to mimic the `mongo` shell [`db.collection.insert()`](https://docs.mongodb.com/manual/reference/method/db.collection.insert/#db.collection.insert) behaviour, in which case the option should perhaps be called `ordered` with a default of `FALSE`.

I think `stop_on_error` is also OK given historical usage (and consistency with tools like `mongoimport`). 

Cheers,
Stennie

**Comment by stennie** [comment]
@jeroen What are next steps for this PR?

Thanks,
Stennie

**Comment by jeroen** [comment]
Merged via https://github.com/jeroen/mongolite/commit/634d9ec3d6ea3eadcb046e903ef08229bc70b362.

**Pull request closed without merging**
